//
//  YSTApiName.h
//  YSTNewGreatWallMedium
//
//  Created by 朱标 on 2017/11/22.
//  Copyright © 2017年 zhubiao. All rights reserved.
//  所有接口

#import <Foundation/Foundation.h>
FOUNDATION_EXPORT NSString *const YST_API_NAME;
//域名
FOUNDATION_EXPORT NSString *const YST_API_URL;
//端口
FOUNDATION_EXPORT NSString *const YST_API_PORT;
//地址
FOUNDATION_EXPORT NSString *const YST_API_URLNAME;
//注册
FOUNDATION_EXPORT NSString *const YST_API_REGISTER;
//好友列表
FOUNDATION_EXPORT NSString *const YST_API_USERCHATS;
//好友信息
FOUNDATION_EXPORT NSString *const YST_API_USERCHAT;
//删除
FOUNDATION_EXPORT NSString *const YST_API_DELUSERCHATS;
//添加好友
FOUNDATION_EXPORT NSString *const YST_API_ADDUSERCHATS;
//历史消息
FOUNDATION_EXPORT NSString *const YST_API_GETHISTORYMESSAGE;
//离线消息
FOUNDATION_EXPORT NSString *const YST_API_OFFLINEMESSAGE;
//删除历史消息
FOUNDATION_EXPORT NSString *const YST_API_DELETEMESSAGE;
//所有聊天群组
FOUNDATION_EXPORT NSString *const YST_API_FINDALLGROUPCHAT;
//解散群组
FOUNDATION_EXPORT NSString *const YST_API_DISSOLVEGROUPCHAT;
//退出群组
FOUNDATION_EXPORT NSString *const YST_API_EXITGROUPHAT;
//加入群聊
FOUNDATION_EXPORT NSString *const YST_API_ADDGROUPCHAT;
//创建群聊
FOUNDATION_EXPORT NSString *const YST_API_CREATEGROUPCHAT;
//邀请用户
FOUNDATION_EXPORT NSString *const YST_API_QUERYUSERLIST;
//获取群组信息
FOUNDATION_EXPORT NSString *const YST_API_FINDROUPDETAIL;
//申请加入
FOUNDATION_EXPORT NSString *const YST_API_JIONGROUCHAT;
//查询待审批人员
FOUNDATION_EXPORT NSString *const YST_API_QUREYAPPROVEDLIST;
//踢出群聊
FOUNDATION_EXPORT NSString *const YST_API_KICKOUTGROUP;
//拒绝用户加入
FOUNDATION_EXPORT NSString *const YST_API_REFUSEUSERJION;
//群管理员同意用户加入群聊室
FOUNDATION_EXPORT NSString *const YST_API_AGREETOJION;
//上传文件域名
FOUNDATION_EXPORT NSString *const YST_API_URLNAMEIMAGE;
//上传文件
FOUNDATION_EXPORT NSString *const YST_API_FILEUPLOAD;
//邀请成员进群（无需同意）
FOUNDATION_EXPORT NSString *const YST_API_INVITINGUSERS;
//禁言
FOUNDATION_EXPORT NSString *const YST_API_PROHIBITUSERSPEAKER;
//解除禁言
FOUNDATION_EXPORT NSString *const YST_API_REMOVEPROHIBITUSERSPEAK;
//私聊列表
FOUNDATION_EXPORT NSString *const YST_API_GETRECENTCONTACTS;

@interface YSTApiName : NSObject
@end


